encoding: utf-8
name: Prajjwal
url: http://prajjwal1.github.io
author:
  name: Prajjwal
  email: removethisifyouarehumanprajjwalin@proton.me
description: AI Resident at Facebook AI Research. Learning to build machines that can see, think, talk and act.
permalink: /posts/:title/
include: ['_pages']
