encoding: utf-8
name: Praj
url: http://prajjwal1.github.io
author:
  name: Praj
  email: removethisifyouarehumanprajjwalin@proton.me
description: Research Engineer at Meta (Gen AI). Learning to build machines that can see, think, talk and act.
permalink: /posts/:title/
include: ['_pages']
